### ISSUE TITLE
TIMSK1, TIFR1 missing for Servo library

### ISSUE THREAD

**Issue by SGStino** [MCUdude/MightyCore#1]
registers TIMSK1 and TIFR1 are required in the Servo.h library, but the constants aren't defined when compiling with MightyCore.

**Comment by MCUdude** [comment]
On what microcontroller did you get the error?

**Comment by SGStino** [comment]
32 16PU

**Comment by MCUdude** [comment]
Found the issue! Needed to add ATmega8535/16/32. Please download the latest version of the core
