### ISSUE TITLE
Noob question: Does it support "normal arduino code"

### ISSUE THREAD

**Issue by hugopilot** [MCUdude/MightyCore#108]
Your provided C libraries look more low-level than I code in. You know, standard Arduino C++.  But does this plugin support that as well? I really want to use the ATMEGA644 but if I could program it as if I am programming a UNO, without low-level AVR code, that would be awesome!

(P.S I don't know where to put this question so I decided to put it here)

**Comment by MCUdude** [comment]
Hi! Yes, MightyCore supports the standard "Arduino language" (or more correct; API). The code you're already written for the uno will most likely work with the ATmega644 without any modifications!

**Comment by hugopilot** [comment]
Good to hear! Thanks for the fast replay
