### ISSUE TITLE
A4 PDF version availability

### ISSUE THREAD

**Issue by szotsaki** [MCUdude/MightyCore#114]
I usually like working with the printed versions of the pin-assignment images. However, the quality of the printed and resized JPG images are not the best and the JPG artefacts are also rather visible.

May I ask if it would be possible to publish a vectorised version of the pin-assignment images? An A4-sized PDF version would have the additional benefit that search would be possible in that.

Thank you very much!

**Comment by MCUdude** [comment]
Here's the exported PDFs.

[MightyCore_DIP40.pdf](https://github.com/MCUdude/MightyCore/files/2299735/MightyCore_DIP40.pdf)
[MightyCore_TQFP44.pdf](https://github.com/MCUdude/MightyCore/files/2299736/MightyCore_TQFP44.pdf)
