### ISSUE TITLE
Not able to upload code to Atmega16

### ISSUE THREAD

**Issue by manasdas17** [MCUdude/MightyCore#115]
Hi, I am using an **ATmega16 with external 16MHz crystal oscillator and using an stk500v2 programmer. But getting this issue. PFA for screenshot**. But i am able to upload  the .hex files generated by Arduino by stk500v2 from ubntu terminal by "avrdude -p atmega16 -P /dev/ttyACM0 -c stk500v2 -v -U flash:w:blink_1tmega16.ino.hex".What is the issue?
![atmega16-arduino-1 8 5](https://user-images.githubusercontent.com/1115602/44654674-18f97380-aa10-11e8-92d6-3d1694aea406.png)

**Comment by prampec** [comment]
Similar problem here with ATmega1284. I have tried to set up things in a breadboard. Burn bootloader was successful. I can upload using programmer, but cannot upload from serial: not in sync: resp=<random>
Serial communication works on 19200, and serial upload resets the MCU as expected.
Using FT232RL serial module on 5V, 10K pullup on reset, 100nF between reset and DTR.
Is there anything I can try out?
![img_20190222_232628](https://user-images.githubusercontent.com/10376327/53275901-2a8cb100-36fd-11e9-92db-ac16a2b59bfe.jpg)

**Comment by martin323232** [comment]
I have the same problem with 1284P. It works fine with Arduino 1.0.5.
Same setup as prampec, except I used 1.05 to bootloaded it.

**Comment by mrguen** [comment]
Hi martin323232,

Did you solve the issue? What do you mean by Arduino 1.0.5 : the IDE (this old?)  or board definitions?

**Comment by prampec** [comment]
My issue was solved at [#136 ](url)

**Comment by mrguen** [comment]
Thanks. The link is dead...

**Comment by prampec** [comment]
(fixed the link above)

**Comment by MCUdude** [comment]
@manasdas17 The issue you're having is because you're trying to upload code using a USB to serial adapter in Arduino IDE. Select your programmer in the Programmers menu and hold shift down while pressing Upload.
