### ISSUE TITLE
115200 Baud Serial issues When using 20mhz external crystal

### ISSUE THREAD

**Issue by NicholasTracy** [MCUdude/MightyCore#116]
Using the 20mhz External crystal option on a custom board with a serial interface.
Tested at 9600 and everything works fine, however when attempting to change Serial.begin() to 115200 nothing comes through at all. 
I've checked the TX0 and RX0 lines with my scope and I see a signal but the decode on my scope can't read it (garbage data or corrupted signal). When using 9600 baud, again everything works as it should and my scope decodes it correctly. 

The project I am working on really needs to work at 115200 in order to do what it needs to do, So I need to figure out how to fix this in short order to meet a deadline. 

Is there an issue with 20mhz and higher serial port speeds?

**Comment by MCUdude** [comment]
20 MHz shouldn't be an issue. It should result in an error of -1.4%. 
Try adding the following line right after Serial.begin().
```
UBRR0 = 0x0015;
```

Or this if the one above doesn't give you any results:
```
UCSR0A &= ~_BV(U2X0);
UBRR0 = 0x000A;
```

**Comment by NicholasTracy** [comment]
Just gave both a try in a test program. No luck.
I'm starting to suspect a hardware issue. Not sure yet thought. My custom board uses 2 optocouplers to isolate a CH340G from the 1284. One for each direction. They are equivalent to the 817. I might have to break out a breadboard to stick a dip 1284 on and test directly off the uart on the chip.

**Comment by MCUdude** [comment]
You should definitely check the optocouplers. BTW can you test 250000 baud as well? This baud rate would be ideal for a 20MHz clock (0% error).

**Comment by MCUdude** [comment]
Did you ever figure this out?

**Comment by NicholasTracy** [comment]
Sorry I haven't had time to troubleshoot the issue, I have a project deadline for a prototype and just settles for 9600 baud for now. I had to make changes to work around it.
