### ISSUE TITLE
debug symbols missing from LTO images

### ISSUE THREAD

**Issue by WestfW** [MCUdude/MightyCore#124]
Recent versions of avr-gcc will not put complete debugging symbols in the .elf file unless given the "-g" option in the compile command.   This is already specified in the MCUdude cores in platform.txt, but when compiling with Link Time Optimization (-flto), it needs to appear in the link command as well, and the link commands are in boards.txt (since it's a menu-controlled option.)

Basically, anywhere in boards.txt that has "-ftlo" should have "-flto -g"

**Comment by MCUdude** [comment]
Thanks for the heads up! The -g flag doesn't cause any issues on older versions of avr-gcc?

**Comment by WestfW** [comment]
No problems that I know of.  Certainly less problems than specifying "-flto" in a compiler version prior to the LTO implementation.  (I *think* that the need for -g to get the debug symbols is slightly older than -flto)

the main result of not having the debug symbols is that "avr-objdump -S" can't figure out which lines go with which object code, so you don't get the nice mixed output...
