### ISSUE TITLE
Pins 8/9 on the Bobuino pinout are ok?

### ISSUE THREAD

**Issue by ImGamez** [MCUdude/MightyCore#126]
Hi.
I was playing with the Arduino UNO schematic and comparing the pins 8 and 9 of the Bobuino pinout with the ATMEGA328p pinout, seems like they are 'swapped', since in the Arduino UNO the pin 8 has the ICP1 'function', and the pin 9 is the OC1A one, but in the Bobuino that 'attributes' or 'functions' are swapped, I wonder if this is ok and why, because if its made for compatibility for UNO scketches and shields, shouldn't go the other way around (ICP1/OC1A pins)?

Images showing what I mean:
![ATMEGA328 pinout](https://user-images.githubusercontent.com/4965415/50196639-1ee9cc00-0301-11e9-9f4e-1a24c9df7709.png)

![ATMEGA1284 Bobuino pinout](https://user-images.githubusercontent.com/4965415/50196643-24dfad00-0301-11e9-9ff0-31bb72c053fb.png)

Thanks!.

**Comment by MCUdude** [comment]
Hi!
The pins are supposed to be swapped like this. The truth is that the Bobuino pinout is far from perfect but it has kinda become a standard on these 40-pin AVRs. This means we're pretty much stuck with the current Bobuino pinout.
