### ISSUE TITLE
Serial upload problem

### ISSUE THREAD

**Issue by prampec** [MCUdude/MightyCore#136]
I have uploaded the boot loader from the Arduino IDE, and a sample program as well with a Programmer provided by MightyCore (using external 8Mhz clock). Everything was fine.
But I cannot upload using serial.
I have traced the communication and it seams like the boot loader doesn't work at all. After reset the code starts immediately instead of waiting for serial upload.
(In the image attached you can see, that 100ms after reset, my program code starts up by sending a serial message (yellow vertical line) instead of waiting for upload request (blue vertical lines).)
Are the fuse bits are set correctly by firmware upload?
Any help is welcomed, thanks!
![NewFile6](https://user-images.githubusercontent.com/10376327/56973454-2c477a80-6b6d-11e9-9eb2-f5eb42500f3c.png)

**Comment by jandrassy** [comment]
if you uploaded a sample program over ISP after the bootloader, then you deleted the bootloader

**Comment by prampec** [comment]
Oops... okay. Confirmed, that this was the problem. But I'm a bit confused. I thought the bootloader is in the very end of the EEPROM.

**Comment by jandrassy** [comment]
the bootloader is at the end of the **flash**.
avrdude sends a command to delete the flash completely
