### ISSUE TITLE
Bootloader options missing in v2.0.1

### ISSUE THREAD

**Issue by wirehead** [MCUdude/MightyCore#142]
This is what I see when I try to configure my board:

![image](https://user-images.githubusercontent.com/653135/59570486-9482ea80-904d-11e9-87ad-8ad1d33d8373.png)

It looks like it's defaulting to bootloader mode always.  This problem seems to be confined to the MightyCore, because I was totally able to use MiniCore just fine.

**Comment by MCUdude** [comment]
If you do a manual install you'll get a bootload option menu. I'll push a new release very soon. It fixes a lot of small bugs and issues.

**Comment by MCUdude** [comment]
v2.0.2 is now available through boards manager. The bootloader menu is now present!
