### ISSUE TITLE
Thank You :D

### ISSUE THREAD

**Issue by leogomide** [MCUdude/MightyCore#145]
Just want to congratulate you for this amazing core, i was able to finish 2 projects that are stuck  with it :)

Seizing the opportunity, i want to ask you if you have plans to make a core for the ATXmega familly of MCUs, i have searched for anything like this, but have no reliable options till now

Best regards and please keep this awesome work <3

**Comment by MCUdude** [comment]
Thanks for the nice words! Great to hear you find MiniCore useful. if your project requires more space or more IO, MightyCore and MegaCore are just as good!

When it comes to ATXmega I don't think you'll see anything coming from me at least. My time is limited, and I've never really found ATXmegas very attractive. if an AVR isn't powerful enough I've usually used an ARM instead.
