### ISSUE TITLE
UART1 on ATmega644A unavailable

### ISSUE THREAD

**Issue by JeWe37** [MCUdude/MightyCore#146]
Despite the ATmega644A(in contrast to the ATmega644) having a second UART port, Serial1 is not defined, as there is no distinction made between them. For me simply selecting the P versions in the menu tweaking the avrdude.conf so as to have the correct device ID does appear to work. A new category for the 644A might be a viable alternative.

**Comment by MCUdude** [comment]
What version of MightyCore are you using? I'm able to compile a sketch with `Serial1` when selecting 644/A in the tools menu

**Comment by JeWe37** [comment]
I was on v2.0.1. With the new version it does indeed compile! Well alright then...

**Comment by MCUdude** [comment]
For reference, ATmega644 was changed to ATmega644a in commit 4d65c3b.
So, did it actually work for you (on the hardware itself)?

**Comment by MCUdude** [comment]
Please re-open if you experience any issues!
