### ISSUE TITLE
SERIAL_PORT_HARDWARE_OPEN not defined

### ISSUE THREAD

**Issue by JeWe37** [MCUdude/MightyCore#148]
The SERIAL_PORT_HARDWARE_OPEN/SERIAL_PORT_HARDWARE_OPEN1 macros typically defined as Serial/Serial1 are not defined in any of the pinout variants. They are supposed to be used to identify serial ports not already occupied and thus available to other libraries. There also are a few other similar defines, it seems that most are implemented for e.g. the Teensy here https://github.com/PaulStoffregen/cores/blob/master/teensy3/pins_arduino.h

**Comment by MCUdude** [comment]
You're right, they are missing.

But I have yet to see them being used to anything yet. Why do we need these?

**Comment by JeWe37** [comment]
I noticed they are required for NeoGPS in my case. I don't know what else uses them.

**Comment by MCUdude** [comment]
Should be fixed now! You can apply this fix by doing a manual install
