### ISSUE TITLE
MightyCore DIP40 Standard Pinout - PCINT labels are incorrect 

### ISSUE THREAD

**Issue by Udayancshah** [MCUdude/MightyCore#149]
MightyCore DIP40 Standard Pinout diagram at bottom has wrong labels (PCINT) on some of the pins. Physical pins 22 to 28 should have labels PCINT16 to PCINT22, instead of currently shown labels PCINT30 to PCINT24 respectively. Kindly rectify as it is misleading. Thank you

**Comment by MCUdude** [comment]
Thanks for notifying me!
