### ISSUE TITLE
can not burn bootloader

### ISSUE THREAD

**Issue by arifainchtein** [MCUdude/MightyCore#150]
Hello,
I am wanting to use a 1284P and burn the bootloader on to it using an Arduino uno as ISP.  I have followed your instructions and install the MightyCore. Everything seems ok, as you can see from the first image
<img width="664" alt="Screen Shot 2019-07-24 at 13 51 08" src="https://user-images.githubusercontent.com/7456552/61764075-33ec8780-ae1b-11e9-9073-f52872c6e998.png">

However, when i try t burn the bootloader, I get an error.  The weird thing is that avrdude is giving the erro that it can not find the USBtiny device.

![Screen Shot 2019-07-24 at 14 00 26](https://user-images.githubusercontent.com/7456552/61764465-b75aa880-ae1c-11e9-85ce-5f5a87b0b428.png)

Do you have any suggestions as to what could be wrng with my setup?

Thanks

**Comment by MCUdude** [comment]
**ArduinoISP** and **Arduino as ISP** is two different type of programmers.

You need to select Arduino as ISP as your programmer.

**Comment by MCUdude** [comment]
Did this solve the issue?

**Comment by arifainchtein** [comment]
sorry, i missed it, yes this resolve the issue. thanks fr the help
