### ISSUE TITLE
how to upload firmware from raspberry pi 

### ISSUE THREAD

**Issue by arifainchtein** [MCUdude/MightyCore#153]
Hello,
I have followed the instructions to  use the mighty-core using the arduino ide and everything is working fine.
That was a prelude to my real design which is to be able to upload firmware via the raspberry pi command line, without using the  Arduino IDE.  
I have already everything in place to upload firmware to Arduino uno and mega via the command line in the raspberry pi.  I have a make file that i just invoke with 
 `make upload`

In the pi user bashrc i have added:
`export BOARD=Uno`

when I use the Uno.  What is the BOARD when using 1284p?

What do I need to do to install and use the might core win the pi using the command line?

thanks

**Comment by MCUdude** [comment]
MightyCore is designed to work with Arduino IDE, not some makefile. If you want to _just_ upload you can use Avrdude directly. If you want to compile too, you can use PlatformIO from the command line.
