### ISSUE TITLE
Interrupts not working on Atmega644pa

### ISSUE THREAD

**Issue by cpsinghopl** [MCUdude/MightyCore#154]
Hello,

Thanks for providing the library. 
Flashed Atmega644PA using ICSP on Arduino UNO (code written & working on UNO), however interrupts are not working. Rest all other functionality is working.
Is there anything extra which needs to be done?

FYI. using Bobuino pinout, LTO disabled, External 16MHZ clock.

Regards

**Comment by MCUdude** [comment]
What package is your 644PA, and what physical pins are you using for interrupts?

**Comment by PiotrC1** [comment]
It's interresting as I use 644PA and interrupts are working in my case.

**Comment by MCUdude** [comment]
I just tested the interrupt pins on a 644PA with both Standard and Bobuino pinout. Everything works just fine. Pretty confident it's not related to MightyCore.
