### ISSUE TITLE
NeoPixel problem

### ISSUE THREAD

**Issue by arifainchtein** [MCUdude/MightyCore#156]
Hello,
I am trying to use a NeoPixel with a 1284P.  I have verified that everything is connected properly because i can set the color for each one (i am using 2) at setup time and they display fine.
the problem is that afterwards they never change.  Is there anything different with the i2c on the 1284 that I might be missing?

thanks

**Comment by MCUdude** [comment]
NeoPixel can be anything. Are you using a WS2812B? 

There's nothing different about the 1284P's i2c interface, but the "Neopixels" I know doesn't use i2c at all.

**Comment by arifainchtein** [comment]
you are right, i had a wiring problem.
