### ISSUE TITLE
12 Mhz with 115200 uploud speed ?

### ISSUE THREAD

**Issue by JensGrabner** [MCUdude/MightyCore#167]
Will, or can you update these isue.

With U2X=1  and UBRR=0xc (12 Decimal) ist thes possible. I use 12Mhz by 3V3 for a long time.
http://www.gjlay.de/helferlein/avr-uart-rechner.html

Thanks for your work.

**Comment by MCUdude** [comment]
Thanks for your input! 12 MHz 115200 bootloaders were added in commit f8868fa.

You'll have to do a manual install if you want the latest changes. A new boards manager release will be available later.
