### ISSUE TITLE
Pinout pic generator

### ISSUE THREAD

**Issue by a7hybnj2** [MCUdude/MightyCore#170]
@MCUdude your cores are amazing and your pinout pictures are perfect! I am using ATTinyCore and realized that some of the chips that are supported do not have pinout pictures. I asked how they generated them and they pointed me to you: [here](https://github.com/SpenceKonde/ATTinyCore/issues/382#issuecomment-574535060)

I was hoping you had a script or something clever to use to create them that you could share. I would be more than happy to do the work in making them.

Let me know. and sorry about hijacking MightyCore but there is no generic 'contact' button.

**Comment by MCUdude** [comment]
See https://github.com/SpenceKonde/ATTinyCore/issues/382
