### ISSUE TITLE
Error during build: fork/exec /bin/avr-g++: no such file or directory

### ISSUE THREAD

**Issue by rejoys-servify** [MCUdude/MightyCore#177]
I am trying to compile sketch for Atmeg16A which is defined in MightyCore, using Arduino CLI.
Everything works fine when I do this on my mac, but throws this "Error during build: fork/exec /bin/avr-g++: no such file or directory" when I try to do the same in my raspberry pi. I am able to compile sketch for builtin boards like uno and mega on my pi. Similar issue are on Arduino forum but for Arduino IDE and the suggested solution I found was to uninstall and reinstall the board files, the IDE itself etc. Any help will be grateful. Thanks in advance.
<img width="820" alt="Screenshot 2020-03-18 at 10 13 08 AM" src="https://user-images.githubusercontent.com/60520843/76926382-38ae0080-6902-11ea-9c25-47c5614a9e4b.png">

**Comment by gferon** [comment]
It looks like you just need to install `arduino:avr` as well. Well, at least it worked for me.

**Comment by ioExpander** [comment]
Same here when running on the arduino package from Arch Linux. It does not bundle Arduino:avr but uses upstream tools. This setup confuses MightyCore.
**I solved it by going to Tools>boards>Board Manager and installing  the latest "Arduino AVR Boards".** 
At least this fixes the issue.
So it seems that the MightyCore package depends on the default Arduino AVR tools. I do not know whether this is good practice.

**Comment by MCUdude** [comment]
The toolchain is usually installed in together with the IDE. However, like @ioExpander mentioned, you can install the Arduino AVR Boards from boards manager if you're having issues.
