### ISSUE TITLE
Suggestion - for parts with weird names for USART registers, but the same function

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MightyCore#184]
On those parts, it would make life easier if you provided #defines for the standard names, which - unless I'm mistaken - I don't think you currently do (ie, for the atmega16 which doesn't have the 0 in it's USART registers, compile a list of them, and #define (registername with 0) (registername without 0). The only tricky one is that one register that has the high-bit nonsense.... I did this in jtag2updi so I could clean up the code everywhere else and get rid of the ATmega16 special cases that littered it's USART code.

**Comment by MCUdude** [comment]
That's a good idea, why haven't I thought of this before? I'll see what I can do!

**Comment by MCUdude** [comment]
I just realized, [I wrote this guide a few years ago](https://github.com/MCUdude/MightyCore/blob/master/Library_porting.md). This could could just be copied into pins_arduino.h and many/most libraries will just work.

> The only tricky one is that one register that has the high-bit nonsense

What register? Would you like to pass me "a pointer" to it? 😉

**Comment by SpenceKonde** [comment]
Atmega16 UCSRC I think it is

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com
