### ISSUE TITLE
Use 7.3.0-atmel3.6.1-arduino7 to fix power.h for 324PB

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MightyCore#186]
Older versions of toolchain's power.h does not support the 324PB - this was one of the patches I got into that version!

**Comment by MCUdude** [comment]
7.3.0-atmel3.6.1-arduino8 is used if you install the latest boards manager release.

**Comment by SpenceKonde** [comment]
Do you mean 7.3.0-atmel3.6.1-arduino7 or is there a new one? My boards manager isn't showing any 7.3.0-atmel3.6.1-arduino8 in the official package index

**Comment by MCUdude** [comment]
Yes, I mean *arduino7. I mixed it up with avrdude-arduino18.

**Comment by SpenceKonde** [comment]
I was excited for a minute there :-P

**Comment by SpenceKonde** [comment]
(the azduino3 toolchain package is running a little over $10/month currently just for bandwidth)

**Comment by MCUdude** [comment]
Whoa! I should put up a script that constantly downloads and delete the downloaded archive to help you out then 😆
