### ISSUE TITLE
Update Ethernet Library

### ISSUE THREAD

**Issue by Flole998** [MCUdude/MightyCore#190]
The currently used ethernet library is outdated and allows a maximum of 4 Sockets. The newer W5500 Chips allow 8 sockets though, and so does the library included with Arduino. I suggest to use that one instead of the current implementation.

**Comment by MCUdude** [comment]
Sorry for the late reply. 

I suggest I remove the Ethernet library completely and instead use the one that ships with Arduino IDE, hosted [here](https://github.com/arduino-libraries/Ethernet).
