### ISSUE TITLE
'c:\Program' is not recognized as an internal or external command, operable command or batch file

### ISSUE THREAD

**Issue by Yohan-Gunawardena** [MCUdude/MightyCore#195]
There is a problem with version 2.0.6. I got the following error message when I try to compile for Atmega32A; 
"'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
exit status 1
Error compiling for board ATmega32."
![02](https://user-images.githubusercontent.com/49124990/99141901-bedb3c00-2675-11eb-9d7b-a36aa65b51a2.png)

The problem fix after I install the old version; 2.0.5
![03](https://user-images.githubusercontent.com/49124990/99141921-e7633600-2675-11eb-8de5-c056ed67eba9.png)

**Comment by MCUdude** [comment]
Is the problem gone if you do an manual install (remove the boards manager install first)? I pushed a fix recently, but I've not pushed a release yet.

**Comment by Yohan-Gunawardena** [comment]
I used the link to install the board. Not the zip file.
![image](https://user-images.githubusercontent.com/49124990/99149643-5ca22b80-26b5-11eb-86fe-aeed1da5cb29.png)

**Comment by MCUdude** [comment]
I'm asking you if you can uninstall the boards manager version to try the manual install version. I believe the bug is gone in the manual install version, but it would be nice if you could test it just to be sure.

If this solves your issue, I'll release v2.0.7 as soon as I can.

**Comment by MCUdude** [comment]
2.0.7 is available through boards manager
