### ISSUE TITLE
How can i use this for Atmega16A?

### ISSUE THREAD

**Issue by LucLe17031999** [MCUdude/MightyCore#201]
I can't use this for Atmega16A, Atmega16 is still ok. 
* All variants - P, PA, A, PB. Select the correct version in the 'Variant' menu
I don't know where to select the correct version.

**Comment by MCUdude** [comment]
ATmega16 and ATmega16A has the same device signature, so there is no need for a variant menu 🙂
Just select ATmega16, and you're good to go.
