### ISSUE TITLE
can't install on 32bit arduino host "Tool avrdude is not available for your operating system."

### ISSUE THREAD

**Issue by clavisound** [MCUdude/MightyCore#207]
Hello there

Latest board definition (v2.1.0) installs fine on Linux 64bit (arduino-1.8.12) but not on 32-bit Linux system (arduino-1.8.12) with error message: `Tool avrdude is not available for your operating system.`

Previous version 2.0.8 installs fine!

**Comment by MCUdude** [comment]
Seems like the latest Avrdude version (6.3.0-arduino18) pulled from Arduino's servers isn't available?
@per1234 do you know anything about this?

**Comment by MCUdude** [comment]
Is probably OK now
