### ISSUE TITLE
Uploading platformio project

### ISSUE THREAD

**Issue by rikben** [MCUdude/MightyCore#214]
Hi,

I've been coding a project in Clion, using PlatformIO. Now that my prototype is finished, I'd like to upload the project to my custom PCB, which is equipped with a ATMEGA1284P (bootloader already installed). I'm uploading using an external FTDI convertor, attached to UART0.

Now I've read something about PlatformIO support, but I can't find the board anywhere. Am I missing something? How should I setup PlatformIO? Do I just use the regular Microchip ATMEGA1284P with modded platformio.ini?

**Comment by MCUdude** [comment]
Read this:
https://github.com/MCUdude/MightyCore/blob/master/PlatformIO.md

**Comment by rikben** [comment]
Thanks for your quick reply. I already looked through that page but didn't figure it out at first. Using the terminal in clion I got it working now. Thanks!
