### ISSUE TITLE
Tools-->Serial Plotter option is not there

### ISSUE THREAD

**Issue by moulisankaran** [MCUdude/MightyCore#218]
Arduino IDE 2.0.0-beta.7 does not have the Tools-->Serial Plotter option at all.

**Comment by per1234** [comment]
@moulisankaran that has nothing to do with MightyCore. It is a deficiency in Arduino IDE 2.x itself, which is already being tracked here:
https://github.com/arduino/arduino-ide/issues/54

For now, you'll need to use the classic Arduino IDE or a standalone alternative if you need Serial Plotter functionality.

**Comment by moulisankaran** [comment]
Sure, thanks for your response.
