### ISSUE TITLE
Additional pin out and variant request.

### ISSUE THREAD

**Issue by markab** [MCUdude/MightyCore#22]
Hello,

I have been looking for a new boot loader and core for my 1284P boards since the old one was broken by 1.6IDE, this looks like it could be a great replacement.

Could you add a pinout variant for octaguino, I have attached the pins_arduino file, and could you make a 16 and 8Mhz variant, I have included my old boards file.

Thanks, looking forward to testing!!

[boards.txt](https://github.com/MCUdude/MightyCore/files/191877/boards.txt)

[pins_arduino.txt](https://github.com/MCUdude/MightyCore/files/191878/pins_arduino.txt)

**Comment by MCUdude** [comment]
Hi! It seems like your Octaguino is using the "Standard" pinout. You'll find the pinout option in the tools menu :smile:

**Comment by markab** [comment]
![img_3890](https://cloud.githubusercontent.com/assets/840477/14079702/92b9446e-f4f7-11e5-84e9-7a2da5e61cdc.jpg)

**Comment by markab** [comment]
Thanks but the built in led is defined on a different port in my file, is it possible to add?

**Comment by MCUdude** [comment]
If you want I can compile a new version of the bootloader where the LED is located at pin 7. The only change you'll need to add to the original pins_arduino.h is located at [line 65 and 66](https://github.com/MCUdude/MightyCore/blob/master/avr/variants/standard/pins_arduino.h#L65). Just replace '0' with '7'.

**Comment by MCUdude** [comment]
here's the bootloader files. Replace the old in **avr/bootloaders/optiboot/atmega1284** ones with these

[Optiboot_Octaguino.zip](https://github.com/MCUdude/MightyCore/files/191925/Optiboot_Octaguino.zip)

**Comment by markab** [comment]
Thanks thats perfect, all working now :) thanks this saved all my boards!!

**Comment by MCUdude** [comment]
Great!
