### ISSUE TITLE
atmega32-mighty-core-ps2-keyboard

### ISSUE THREAD

**Issue by madhavanatmel** [MCUdude/MightyCore#221]
hi, i am trying to connect ps2 keyboard in atmega32 and using pin no . 16&17 as Arduino pin 10&11 for ps2 keyboard Data pin & IRQ Pin . But i couldn't get any keycode in the serial monitor . at the beginning KEYBOARD test message is from m32 after that nothing is coming .
![image](https://user-images.githubusercontent.com/82223872/130714080-34765689-3f2e-464e-a792-d1bf2ef0d12e.png)
the same keyboard and ps2 keyboard library working well with uno using Arduino pin as 2& 3

**Comment by madhavanatmel** [comment]
Good that now working ..
#elif defined(__AVR_ATmega644P__) || defined(__AVR_ATmega32__) // Sanguino.
standard pin layout .

**Comment by MCUdude** [comment]
Great to hear!
