### ISSUE TITLE
 multiple definition of `__vector_4'

### ISSUE THREAD

**Issue by kang2k10** [MCUdude/MightyCore#232]
I use SoftwareSerial library, and Encoder library
if in sketch

```
ISR (PCINT0_vect) {
  newPos = myEnc.read();
}
```

compiling with error
SoftwareSerial.cpp:239: multiple definition of `__vector_4'

Pin for rx-10, tx-11
Encoder A4,A5
Atmega644a
How fix this ?

**Comment by MCUdude** [comment]
The dumb thing about the SoftwareSerial library is that is occupies all the PCINT interrupt vectors. You can modify the library and remove ISR(PCINT0_vect) if PCINT0 is used with the encoder

**Comment by kang2k10** [comment]
Thanks. I  modify library, and all work.
