### ISSUE TITLE
OSCCAL byte atmega16

### ISSUE THREAD

**Issue by Harshal-Sakhale** [MCUdude/MightyCore#242]
I have greatly benefited by the atmega16 optiboot boot loader source running at internal 8 MHz. However I realized much later to use it correctly you need to read osccal byte and load it at runtime to calibrate the oscillator. Is it already documented somewhere in the repository ?

**Comment by MCUdude** [comment]
You don't _have_ to calibrate the internal oscillator if you're not using it for timing-sensitive applications. It is up to the user how it would like to deal with OSCCAL, and it is well documented in the microcontroller datasheet, but not in this repo.
