### ISSUE TITLE
 compile error for Atmega1284 and Atmega32

### ISSUE THREAD

**Issue by rommil67** [MCUdude/MightyCore#247]
I have a compile error like this:

Compiling the core ...
"C: \\ Users \\ rommi \\ AppData \\ Local \\ Arduino15 \\ packages \\ arduino \\ tools \\ avr-gcc \\ 7.3.0-atmel3.6.1-arduino7 / bin / avr-gcc" -c -g -assembler-with-cpp -mmcu = atmega1284p -DF_CPU = 1600000L -DARDUINO = 10819 -DARDUINO_AVR_ATmega1284 -DARDUINO_ARCH_AVR "-IC: \\ Users \\ rommi \\ AppData \\ in Local \\ Ardu \\ in Local\ Ardu \\ in \ MightyCore \\ hardware \\ avr \\ 2.1.3 \\ cores \\ MCUdude_corefiles "" -IC: \\ Users \\ rommi \\ AppData \\ Local \\ Arduino15 \\ packages \\ MightyCore \\ hardware \\ avr \\ 2.1.3 \\ variants \\ standard "" C: \\ Users \\ rommi \\ AppData \\ Local \\ Arduino15 \\ packages \\ MightyCore \\ hardware \\ avr \\ 2.1.3 \\ cores \\ MCUdude_corefiles \\ wiring_pulse.S "-o" C: \\ Users \\ rommi \\ AppData \\ Local \\ Temp \\ arduino_build_408757 \\ core \\ wiring_pulse.S.o "
avr-gcc: error: unrecognized command line option "-assembler-with-cpp"
library Control-Surface-main version 2.0.0 with Use \ Usage \ OneDrive \ Documents \ Arduino \ libraries \ Libraries \ Surface-main
Using the 1.0 SPI library from the file: C: \ Users \ Users \ Local \ Ardu15 \ packages \ hardware \ avr \ 2.1.3 \ libraries
output 1 state
Compilation error for ATmega1284 boar

**Comment by MCUdude** [comment]
Good to hear you figured it out!
