### ISSUE TITLE
Error Compiling Attmega664a "No SPI Pins Defined" 

### ISSUE THREAD

**Issue by link0687** [MCUdude/MightyCore#248]
Hello,

I am trying to run FastLed with ATTmega664a however it looks like the a version has not been added as the the P & PA modes can compile without a problem. Error message ""No hardware SPI pins defined. All SPI access will default to bitbanged output"

Is there any chance this can be added or I can add it?

Thanks,

**Comment by MCUdude** [comment]
You'll have to report the issue over at the FastLED repo. There's nothing I can do about this unfortunately.
Ask then to add support for ATmega644 and ATmega644A.
