### ISSUE TITLE
Board manager url

### ISSUE THREAD

**Issue by boelle** [MCUdude/MightyCore#25]
awesome hardware definition file set

while you can just put them in hardware folder one wish from me would be a board manager url.... 

will try and see if i can make one

**Comment by per1234** [comment]
Already done: https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json

**Comment by boelle** [comment]
:-D

he should put that on the readme here in git also

**Comment by per1234** [comment]
It is, see the Boards Manager Installation subsection of the How to install section of the readme.

**Comment by boelle** [comment]
doooh !!
