### ISSUE TITLE
how to use another programmer?

### ISSUE THREAD

**Issue by rocifier** [MCUdude/MightyCore#251]
Hi I want to use MightCore because it's the only one which supports Atmega324P. But My programmer is FTL32 and that doesn't show up on the Programmer list in arduino IDE. How can I add a different programmer protocol?

**Comment by MCUdude** [comment]
I've never heard of the FTL32, but if the programmer is not in the Programmers list, you can export the compiled hex file and upload it to the microcontroller using a 3rd party tool like Avrdude.

Compile your sketch and click "Sketch > Export compiled Binary" to get the hex file.
