### ISSUE TITLE
I cant compile code using mighty core even tho the code compilers using normal arduino , error exec: "cmd": executable file not found in %PATH%

### ISSUE THREAD

**Issue by bedoman5** [MCUdude/MightyCore#272]
Arduino: 1.8.19 (Windows 10), Board: "ATmega32, Yes (UART0), EEPROM retained, Standard pinout, BOD 2.7V, LTO disabled, External 16 MHz"

Arduino: 1.8.19 (Windows 10), Board: "ATmega32, Yes (UART0), EEPROM retained, Standard pinout, BOD 2.7V, LTO disabled, External 16 MHz"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\user\AppData\Local\Arduino15\packages -hardware C:\Users\user\Documents\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\user\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\user\Documents\Arduino\libraries -fqbn=MightyCore-2.2.1:avr:32:bootloader=uart0,eeprom=keep,pinout=standard,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10819 -build-path C:\Users\user\AppData\Local\Temp\arduino_build_793691 -warnings=none -build-cache C:\Users\user\AppData\Local\Temp\arduino_cache_792028 -prefs=build.warn_data_percentage=75 -verbose C:\Users\user\Desktop\graduation project\code\front32\front32.ino

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\user\AppData\Local\Arduino15\packages -hardware C:\Users\user\Documents\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\user\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\user\Documents\Arduino\libraries -fqbn=MightyCore-2.2.1:avr:32:bootloader=uart0,eeprom=keep,pinout=standard,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10819 -build-path C:\Users\user\AppData\Local\Temp\arduino_build_793691 -warnings=none -build-cache C:\Users\user\AppData\Local\Temp\arduino_cache_792028 -prefs=build.warn_data_percentage=75 -verbose C:\Users\user\Desktop\graduation project\code\front32\front32.ino

Using board '32' from platform in folder: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr

Using core 'MCUdude_corefiles' from platform in folder: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr

Detecting libraries used...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o nul

Alternatives for mcp_can.h: [MCP_CAN_lib-1.5.0@1.5.0]

ResolveLibrary(mcp_can.h)

  -> candidates: [MCP_CAN_lib-1.5.0@1.5.0]

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "-IC:\\Users\\user\\Documents\\Arduino\\libraries\\MCP_CAN_lib-1.5.0" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o nul

Alternatives for SPI.h: [SPI@1.0]

ResolveLibrary(SPI.h)

  -> candidates: [SPI@1.0]

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "-IC:\\Users\\user\\Documents\\Arduino\\libraries\\MCP_CAN_lib-1.5.0" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\SPI\\src" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o nul

Alternatives for Wire.h: [Wire@1.1]

ResolveLibrary(Wire.h)

  -> candidates: [Wire@1.1]

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "-IC:\\Users\\user\\Documents\\Arduino\\libraries\\MCP_CAN_lib-1.5.0" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\SPI\\src" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\Wire\\src" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o nul

Using cached library dependencies for file: C:\Users\user\Documents\Arduino\libraries\MCP_CAN_lib-1.5.0\mcp_can.cpp

Using cached library dependencies for file: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr\libraries\SPI\src\SPI.cpp

Using cached library dependencies for file: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr\libraries\Wire\src\Wire.cpp

Using cached library dependencies for file: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr\libraries\Wire\src\utility\twi.c

Generating function prototypes...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "-IC:\\Users\\user\\Documents\\Arduino\\libraries\\MCP_CAN_lib-1.5.0" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\SPI\\src" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\Wire\\src" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\preproc\\ctags_target_for_gcc_minus_e.cpp"

"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Compiling sketch...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++17 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\cores\\MCUdude_corefiles" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\variants\\standard" "-IC:\\Users\\user\\Documents\\Arduino\\libraries\\MCP_CAN_lib-1.5.0" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\SPI\\src" "-IC:\\Users\\user\\Documents\\Arduino\\hardware\\MightyCore-2.2.1\\avr\\libraries\\Wire\\src" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp" -o "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp.o"

Compiling libraries...

Compiling library "MCP_CAN_lib-1.5.0"

Using previously compiled file: C:\Users\user\AppData\Local\Temp\arduino_build_793691\libraries\MCP_CAN_lib-1.5.0\mcp_can.cpp.o

Compiling library "SPI"

Using previously compiled file: C:\Users\user\AppData\Local\Temp\arduino_build_793691\libraries\SPI\SPI.cpp.o

Compiling library "Wire"

Using previously compiled file: C:\Users\user\AppData\Local\Temp\arduino_build_793691\libraries\Wire\Wire.cpp.o

Using previously compiled file: C:\Users\user\AppData\Local\Temp\arduino_build_793691\libraries\Wire\utility\twi.c.o

Compiling core...

Using precompiled core: C:\Users\user\AppData\Local\Temp\arduino_cache_792028\core\core_c3d3e8e5d234599865ca89358242e11c.a

Linking everything together...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-gcc" -w -Os -Wl,--gc-sections,--section-start=.FAR_MEM1=0x10000 -mmcu=atmega32 -o "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.elf" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\sketch\\front32.ino.cpp.o" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\libraries\\MCP_CAN_lib-1.5.0\\mcp_can.cpp.o" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\libraries\\SPI\\SPI.cpp.o" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\libraries\\Wire\\Wire.cpp.o" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691\\libraries\\Wire\\utility\\twi.c.o" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/..\\arduino_cache_792028\\core\\core_c3d3e8e5d234599865ca89358242e11c.a" "-LC:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691" -lm

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.elf" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.eep"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-objcopy" -O ihex -R .eeprom "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.elf" "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.hex"

cmd /C echo. && "C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-objdump" --disassemble --source --line-numbers --demangle --section=.text "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino.elf" > "C:\\Users\\user\\AppData\\Local\\Temp\\arduino_build_793691/front32.ino_atmega32_16000000L.lst"

Using library MCP_CAN_lib-1.5.0 at version 1.5.0 in folder: C:\Users\user\Documents\Arduino\libraries\MCP_CAN_lib-1.5.0 

Using library SPI at version 1.0 in folder: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr\libraries\SPI 

Using library Wire at version 1.1 in folder: C:\Users\user\Documents\Arduino\hardware\MightyCore-2.2.1\avr\libraries\Wire 

exec: "cmd": executable file not found in %PATH%

Error compiling for board ATmega32.

**Comment by MCUdude** [comment]
Try updating to the latest MightyCore boards manager version, v2.2.3

**Comment by bedoman5** [comment]
@MCUdude i was originally using the newest version same problem

**Comment by MCUdude** [comment]
Have you installed Mightycore using the boards manager?

**Comment by bedoman5** [comment]
@MCUdude yes i installed it two times, first time using the board manager and the second manually i get the same problem

**Comment by MCUdude** [comment]
I think @per1234 found a solution to this a while ago. I donæt remember exactly what he did to fix it, but the root cause is that the `cmd` command it not in the Windows environment variables.

**Comment by bedoman5** [comment]
![image](https://github.com/MCUdude/MightyCore/assets/120425957/cd7e020e-28c0-4045-8f05-1e09bf888296)
i solved the problem inside the system variables i changed the name for the cmd to be like what is shown in the photo. thanks for your time ❤

**Comment by MCUdude** [comment]
Excellent! It was a Windows setting then. Great to hear you figured it out! Thanks for using MightyCore 🙂
