### ISSUE TITLE
Perhaps some setting of the delay/clock functions need to be revised.

### ISSUE THREAD

**Issue by rtek1000** [MCUdude/MightyCore#273]
In the simulation the MCU Atmega1284, Atmega644, Atmega324 and Atmega164 didn't even oscillate the pin to flash the LED.

I managed to make the Atmega1284 work using MPLAX and XC8.

https://github.com/MCUdude/MightyCore/issues/241

MPLABX reference (Atmel Studio code): https://circuitdigest.com/microcontroller-projects/how-to-program-avr-microcontroller-atmega16-with-usbasp-programmer-using-atmel-studio

[ATmega16_blink.X.zip](https://github.com/MCUdude/MightyCore/files/11521375/ATmega16_blink.X.zip)
[Atmega1284_blink.X.zip](https://github.com/MCUdude/MightyCore/files/11521376/Atmega1284_blink.X.zip)

**Comment by MCUdude** [comment]
See reply in #241. I have no idea why the Proteus doesn't with MightyCore, but you're welcome so submit a PR if you think you know how to resolve the issue

**Comment by rtek1000** [comment]
Thank you for your attention. I believe that other users also stopped using this core because it was not possible to simulate the circuit. I hope someone can resolve this in the future.
