### ISSUE TITLE
No variants for ATmega32?

### ISSUE THREAD

**Issue by hilmiyafia** [MCUdude/MightyCore#280]
I don't see the variants option for ATmega32. I want to program ATmega32A, is it the same?

**Comment by MCUdude** [comment]
It's right there in the documentation:

<img width="701" alt="image" src="https://github.com/MCUdude/MightyCore/assets/3238730/7426393a-6d3f-4937-a9fc-1e00ce6b4982">

ATmega32A are binary compatible with ATmega32, and ca be used without any issues.

**Comment by hilmiyafia** [comment]
Thank you! 😊
