### ISSUE TITLE
Keep failure to flash the optiboot loader to the ATMEGA128P

### ISSUE THREAD

**Issue by unebonnevie** [MCUdude/MightyCore#282]
Hi,
I am using the ATMEGA1284P and have followed the instructions to get the bootloader flashed.   My 1284P is programmed with 0xCE as the low fuse byte and 0xD9 as the high fuse byte.  I have it use a 16Mhz external crystal.

I keep getting the below failure while flashing the bootloader.  It doesn ot matter what 16Mhz 1284P board choice I choose.

I do have a 100nF capacitor between the DTR or RTS line on my USB to serial adapter and to the RESET pin on the 1284P's reset pin.

![image](https://github.com/MCUdude/MightyCore/assets/14103779/9b4e3151-d6f0-40f6-9b53-3899a387fd2c)

Please see the image attached.  It's trying to flash a bootloader of 131702 bytes.  That's big!

Thanks for any tip!

![image](https://github.com/MCUdude/MightyCore/assets/14103779/d8d9b6e4-73e5-47b6-8def-e625291c4acc)

`avrdude: Using SCK period of 10 usec
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9705 (probably m1284p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: Using SCK period of 10 usec
avrdude: reading input file "C:\Users\asle\dev\arduino\hardware\mighty-1284p\avr/bootloaders/optiboot/optiboot_atmega1284p.hex"
avrdude: writing flash (131072 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 131072 bytes of flash written
avrdude: verifying flash memory against C:\Users\asle\dev\arduino\hardware\mighty-1284p\avr/bootloaders/optiboot/optiboot_atmega1284p.hex:
avrdude: load data flash data from input file C:\Users\asle\dev\arduino\hardware\mighty-1284p\avr/bootloaders/optiboot/optiboot_atmega1284p.hex:
avrdude: input file C:\Users\asle\dev\arduino\hardware\mighty-1284p\avr/bootloaders/optiboot/optiboot_atmega1284p.hex contains 131072 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x1fc00
         0xff != 0x11
avrdude: verification error; content mismatch

avrdude done.  Thank you.

Error while burning bootloader.`

**Comment by unebonnevie** [comment]
Although I get a verification error when flashing the bootloader (see original post), I am actually able to flash any firmware on my 1284P via the bootloader in using the Arduino IDE's upload menu choice.


avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9705 (probably m1284p)
avrdude: reading input file "C:\Users\asle\AppData\Local\Temp\arduino_build_733264/listfiles.ino.hex"
avrdude: writing flash (11156 bytes):

Writing | ################################################## | 100% 0.55s

avrdude: 11156 bytes of flash written
avrdude: verifying flash memory against C:\Users\asle\AppData\Local\Temp\arduino_build_733264/listfiles.ino.hex:
avrdude: load data flash data from input file C:\Users\asle\AppData\Local\Temp\arduino_build_733264/listfiles.ino.hex:
avrdude: input file C:\Users\asle\AppData\Local\Temp\arduino_build_733264/listfiles.ino.hex contains 11156 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.26s

avrdude: verifying ...
avrdude: 11156 bytes of flash verified

avrdude done.  Thank you.

**Comment by MCUdude** [comment]
But you aren't even using MightyCore!
_Mighty Mini 1284p @ 16MHz, Optiboot @ 1Mbps_ is from another Arduino core

**Comment by unebonnevie** [comment]
Hi,

![image](https://github.com/MCUdude/MightyCore/assets/14103779/3397d96a-0a27-40ba-a91d-74784ffcfe9a)

Also ready installed.  I am going to update.

![image](https://github.com/MCUdude/MightyCore/assets/14103779/236a3a9b-10b2-40cf-a524-a1ee21165a0b)

After updating I now have a "MightyCore" menu item in the "Boards" menu.

![image](https://github.com/MCUdude/MightyCore/assets/14103779/8bfb5f63-a97f-434d-88b7-68463b621aa9)

**Comment by MCUdude** [comment]
You'll probably have to switch USB drivers. Download [Zadig](https://zadig.akeo.ie) and switch to `libusbK` I think.
