### ISSUE TITLE
Error while burning bootloader (while using v3.0)

### ISSUE THREAD

**Issue by jpalepu** [MCUdude/MightyCore#286]
I am using the usbTiny ESP programmer with MightyCore v3.0 and I get the following error when I try to burn the bootloader. 

`avrdude warning: cannot open USB device: Permission denied
avrdude error: cannot find USBtiny device (0x1781/0xc9f)
avrdude error: unable to open programmer usbtiny on port usb
Error while burning bootloader.`

What is more strange is that, everything works perfectly fine while using the MightyCore v2.1.3. 

Any help is appreciated.

**Comment by MCUdude** [comment]
I'll assume you're using Windows. MightyCore v2.1.3 uses Avrdude 6.3, while MightyCore v3.0.0 uses Avrdude 7.2.
You might have to switch USB drivers on Windows to get it to work with Avrdude 7+.

Download Zadig, select the USBtiny in the device list, and try switching to WinUSB or libusbK.
https://zadig.akeo.ie
