### ISSUE TITLE
Incorrect digitalPinToPCMSK macro in standard variant

### ISSUE THREAD

**Issue by per1234** [MCUdude/MightyCore#34]
https://github.com/MCUdude/MightyCore/blob/master/avr/variants/standard/pins_arduino.h#L89-L90 is:
```c
#define digitalPinToPCICRbit(p) (((p) <= 7) ? 1 : (((p) <= 15) ? 3 : (((p) <= 23) ? 2 : 0)))
#define digitalPinToPCMSK(p)    (((p) <= 7) ? (&PCMSK2) : (((p) <= 13) ? (&PCMSK0) : (((p) <= 21) ? (&PCMSK1) : ((uint8_t *)0))))
```
but https://github.com/JChristensen/mighty-1284p/blob/v1.6.3/avr/variants/standard/pins_arduino.h#L67-L68 is:
```c
#define digitalPinToPCICRbit(p) ( (p) <= 7 ? 1 : (p) <= 15 ? 3 : (p) <= 23 ? 2 : 0 )
#define digitalPinToPCMSK(p)    ( (p) <= 7 ? &PCMSK1 : (p) <= 15 ? &PCMSK3 : (p) <= 23 ? &PCMSK2 : &PCMSK0 )
```
It seems to me that Mighty 1284P's macro is correct.

Reported at http://forum.arduino.cc/index.php?topic=262983.msg2893480#msg2893480

**Comment by MCUdude** [comment]
Thanks for reporting! It should be OK now 👍
