### ISSUE TITLE
get rid of warnings

### ISSUE THREAD

**Issue by zevero** [MCUdude/MightyCore#41]
just remove the const on returning by value :)
```
/home/severin/.arduino15/packages/MightyCore/hardware/avr/1.0.7/libraries/EEPROM/src/EEPROM.h:43:30: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     operator const uint8_t() const       { return **this; }
                              ^
/home/severin/.arduino15/packages/MightyCore/hardware/avr/1.0.7/libraries/EEPROM/src/EEPROM.h:92:26: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     operator const int() const          { return index; }
                          ^
```

**Comment by MCUdude** [comment]
@Chris--A will this affect the code in any way?

**Comment by MCUdude** [comment]
Hmm. I'm one getting an error when doing that. Is is "safe" @Chris--A ?

**Comment by zevero** [comment]
I am sorry ... its an issue with the EEPROM library ... not with MightyCore

**Comment by MCUdude** [comment]
No problem! I include the library in the core, so I'll update it if @Chris--A have a proper fix for it 😉

**Comment by Chris--A** [comment]
Yeah I have an update in the mix. This and other warnings are fixed.
Also have a few more additions.
Been flat out the last few weeks, will do a PR on Friday/Saturday
Cheers
