### ISSUE TITLE
TQFP pinout drawings have incorrect numbering

### ISSUE THREAD

**Issue by Alftron** [MCUdude/MightyCore#48]
I've just noticed that the drawings of the TQFP standard and bobuino pin outs are numbered incorrectly. Where the corner is labelled pin 21, this should be labeled pin 22. This in turn throws out the numbering for pins 23, 33 and 34.

**Comment by MCUdude** [comment]
Great catch, fixed!
Thanks 😃

**Comment by Alftron** [comment]
Great, thanks for the brilliant work!
