### ISSUE TITLE
LowPower Library compiling error

### ISSUE THREAD

**Issue by rickhank2016** [MCUdude/MightyCore#49]
I have an Atmega324 on breadboard and I have problem when compile in Arduino IDE.
I have modified this line in LowPower.h file:

	#if defined (__AVR_ATmega328P__) || defined (__AVR_ATmega168__) || defined (__AVR_ATmega324P__) 

but the error remain

this is the error:
/Users/yakamoz/Documents/DOCUMENTI 2016/Arduino/libraries/Low-Power/LowPower.h:144:6: error: #error "Please ensure chosen MCU is either 168, 328P, 32U4, 2560 or 256RFR2."
     #error "Please ensure chosen MCU is either 168, 328P, 32U4, 2560 or 256RFR2."
  
How can I solve and put MCU in PowerDown ?

**Comment by MCUdude** [comment]
What kind of ATmega324 do you have? ATmega324A, ATmega324P or ATmega324PA?
Do you have a link to the library?

**Comment by rickhank2016** [comment]
I have ATmega324P, I have discovered problem, was that my IDE take library in another place.
Now is ok

**Comment by rickhank2016** [comment]
thank you very much

**Comment by SkeyPr** [comment]
> 

Hello I am quite late to this discussion but could you please guide me about how you fixed the problem? I am facing the same problem as you were, "Please ensure chosen MCU is either 88, 168, 168P, 328P, 32U4, 2560 or 256RFR2." and would really appreciate if you could help

thanks
