### ISSUE TITLE
Adding couple chips

### ISSUE THREAD

**Issue by Miykaelpoly** [MCUdude/MightyCore#59]
Sorry to bother you, but would it be possible to add the support for ATmega 16/32 u4 chips? the 32 one is the one arduino uses in its micro board, so there should be plenty of already existing data, but I cant find a barebones one for them.

**Comment by MCUdude** [comment]
Hi!
It's true that there doesn't exst any barebone hardware package for these chips. It should totally be doable, but I don't think they belong to MightyCore, but rather their own core.

They all come in 44 pin TQFP packages, but that's where the similarities ends. They have completly different  pinout and pheripherals, and does not belong to the same AVR family.

If you want to get your hands a little dirty you could fork [MiniCore](https://github.com/MCUdude/MiniCore), remove ATmega8,48,88,168,328 from the boards.txt file and add ATmega16u4 and ATmega32u4. You can find the bootloader and pin definition for them over at the [Arduino repo](https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr).
