### ISSUE TITLE
TX/RX pin assignments for FTDI programming on 1284p QFN standard layout

### ISSUE THREAD

**Issue by FedorAdarichev** [MCUdude/MightyCore#74]
Hello,

Two questions:
1.  Do the TX/RX connections from an FTDI programmer have to connect to pins 10 and 9 respectively (TXD0 and RXD0), or can they ALSO alternatively be connected to pins 12 and 11 (TXD1 and RXD1) to upload Arduino sketches successfully?
2.  If not, where exactly in the bootloader files can I view this pinout assignment, and is it possible for me to rewrite the pin assignments to make it 11 and 12 instead?

**Comment by MCUdude** [comment]
Hi!

The ATmega1284p supports serial uploading using pin 9+10 (UART0) and pin 11+12 (UART1). This is determined by the bootloader. MightyCore dues not support code upload using UART1, but you can easily re-compile the bootloader if you really need it.

Another user just forked MightyCore to make use of UART1 for uploading. You can find this fork here:
[https://github.com/epccs/MightyCore](https://github.com/epccs/MightyCore)
