### ISSUE TITLE
ide 1.6.11 ubuntu

### ISSUE THREAD

**Issue by comarius** [MCUdude/MightyCore#88]
Tools > Board > Boards Manager...  is missing ?
Installed manually. Then 324 is missing form boards ?

**Comment by MCUdude** [comment]
what?

**Comment by MCUdude** [comment]
Install the latest IDE. There's no reason to not run the latest version.

If you've done a manual install you'll find ATmega324 under Tools > Boards. 
Note that ATmega324PB is not supported.
<img width="315" alt="skjermbilde 2018-03-24 16 26 33" src="https://user-images.githubusercontent.com/3238730/37865666-243f7376-2f80-11e8-9679-6cb089eb8ccd.png">

**Comment by comarius** [comment]
Thank you. Closed.
