### ISSUE TITLE
PWM on C2/C3 at atmega32

### ISSUE THREAD

**Issue by mirko314** [MCUdude/MightyCore#9]
Hello,
I don't know if this is the appropiate location to ask this. If not just let me know.
I found your Git-Repo and it works like a charm. I got a PCB with an **ATmega32L** and I need PWM output on **PORT C2 and PORT C3**. Do you have any Idea how to provide some functionality so that I could drive Motors with different Speed on these Ports? It does not even need a really high Frequency.
Kind regards,
Mirko

**Comment by MCUdude** [comment]
There's no hardware PWM support on PC2 and PC3. You can always bitbang a PWM signal. Try searching for "Arduino soft PWM"

**Comment by mirko314** [comment]
Thank you for clarifying!
Kind Regards
