### ISSUE TITLE
OTA for avrs

### ISSUE THREAD

**Issue by isnadh** [MCUdude/MightyCore#96]
Could you kindly implement ota for avr on esp8266 for avr-esp8266 combo. Thanks

**Comment by MCUdude** [comment]
Hi!
As far as I know you can use the [ESP8266 as an AVR programmer](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266AVRISP) for any AVR you'd like. However I will not implement some kind of special OTA feature for this core.
