### ISSUE TITLE
Typo on boards.txt - 1284 18.432mhz

### ISSUE THREAD

**Issue by airzone-sama** [MCUdude/MightyCore#99]
Hi Guys,

Line 112 in boards.txt reads:
`1284.menu.clock.18_432MHz_external.bootloader.low_fuses=f7`
AVR dude spits the dummy when uploading the bootloader in arduino.

It should read this:
`1284.menu.clock.18_432MHz_external.bootloader.low_fuses=0xf7`

**Comment by MCUdude** [comment]
Thanks for reporting! Will fix it soon
